version: '3.5'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    networks:
      bdfi_network:
        ipv4_address: 172.23.0.5   
    ports:
    - '27017-27019:27017-27019'
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    container_name: spark-master
    networks:
      bdfi_network:
        ipv4_address: 172.23.0.3    
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ~/big_data:/big_data
    environment:
      - 'INIT_DAEMON_STEP=setup_spark'
      - 'constraint:node==<yourmasternode>'
    mem_limit: 500m
    mem_reservation: 100m
  spark-worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-1
    networks:
      bdfi_network:
        ipv4_address: 172.23.0.4    
    depends_on:
      - spark-master
    volumes:
      - ~/big_data:/big_data
    mem_limit: 500m
    mem_reservation: 100m
  spark-worker-2:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-2
    networks:
      bdfi_network:
        ipv4_address: 172.23.0.10    
    depends_on:
      - spark-master
    volumes:
      - ~/big_data:/big_data
    environment:
      - 'SPARK_MASTER=spark://spark-master:7077'
      - 'constraint:node==<yourworkernode>'
    mem_limit: 500m
    mem_reservation: 100m
  zookeeper:
    container_name: zookeeper
    networks:
      bdfi_network:
        ipv4_address: 172.23.0.6   
    image: zookeeper:3.6.2
    ports: 
      - '2181:2181'
  kafka:
    image: 'wurstmeister/kafka:2.12-2.3.0'
    container_name: kafka
    networks:
      bdfi_network:
        ipv4_address: 172.23.0.2    
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.23.0.2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  spark-submit:
    container_name: spark-submit
    image: bde2020/spark-submit:2.4.4-hadoop2.7
    ports:
      - '4040:4040'
    volumes:
      - ~/big_data:/big_data
    environment: 
      - 'SPARK_HOME=/spark'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/spark/bin:/spark/sbin:/spark/python'
      - 'PYSPARK_PYTHON=/usr/bin/python3'
      - 'JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk'
      - 'PROJECT_HOME=/big_data'
    networks:
      bdfi_network:
        ipv4_address: 172.23.0.7
    mem_limit: 300m
    mem_reservation: 100m
  flask:
    container_name: flask
    image: flask:1.0
    build:
      context: ~/big_data/
      dockerfile: Dockerfile
    environment: 
      - 'PROJECT_HOME=/big_data'
    networks:
      bdfi_network:
        ipv4_address: 172.23.0.8 
    mem_limit: 300m
    mem_reservation: 100m
  nginx:
    container_name: nginx
    image: bunkerity/bunkerized-nginx
    environment: 
      - 'USE_REVERSE_PROXY=yes'
      - 'REVERSE_PROXY_URL=/'
      - 'REVERSE_PROXY_HOST=http://172.23.0.8:5000'  
    ports: 
      - '80:5000'
networks:
  bdfi_network:
    driver: bridge
    name: bdfinetwork
    ipam: 
      config: 
        - subnet: 172.23.0.0/24